version: "3.3"
services:
  app-frontend:
    stdin_open: true
    container_name: devinhouse-frontend
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - 3000:3000
    volumes:
      - "/app/node_modules"
      - "./:/app"
  app-backend:
    container_name: devinhouse-backend
    image: gcpasquadproduto/softplan-desafio-frontend
    ports:
      - 3002:3002